#!/bin/bash

module load bioinfo-tools
module load Pilon

dir=~/genome-analysis/analyses

# Align the paired illumina reads to a PacBio assembly generated by Canu. 
dir_align=$dir/01_preprocessing/illumina-bwa

pilon \
    --genome $dir/02_genome_assembly/pilon_assembly/rerun.pilon.fasta \
    --frags $dir_align/SRR6058604-aln-sorted.bam \
    --changes \
    --output rerun_1.pilon \
    --outdir $dir/02_genome_assembly/pilon_assembly/ \
    --fix all \
    --threads 8 \
    --diploid
